apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x184bszus-python 
  janus-idp.io/tekton: x184bszus-python
  backstage.io/kubernetes-id: x184bszus-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x184bszus-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml