apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x184bszus-python
  janus-idp.io/tekton: x184bszus-python
  backstage.io/kubernetes-id: x184bszus-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x184bszus-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
