apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x184bszus-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x184bszus-python 
  name: x184bszus-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: x184bszus-python 
